name: job-board

x-django: &django
  build: .
  working_dir: /app/
  volumes:
    - ./app:/app
  env_file:
    - ./.env
  restart: always


services:
  app:
    <<: *django
    command: /bin/bash /app/bin/boot.sh
    expose:
      - 8001  # <= nginx:8080
    depends_on:
      db:
        condition: service_healthy

  db:
    image: postgres:15
    restart: always
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    env_file:
      - ./db.env
    ports:
     - 15432:5432
    healthcheck:
      test: pg_isready -d $$POSTGRES_DB -U $$POSTGRES_USER
      interval: 1s
      timeout: 5s
      retries: 10

  nginx:
    build: ./nginx
    restart: always
    ports:
      - 18080:8080  # => app:8001
    expose:
      - 8080
    volumes:
      - ./app/staticfiles:/staticfiles:ro
    depends_on:
      - app

  redis:
    image: redis:latest
    restart: always
    expose:
      - 6379
    command: redis-server
    volumes:
      - redis_data:/data


  celery_worker:
    <<: *django
    command: celery -A core worker -l INFO
    depends_on:
      - redis
      - db

  celery_beat:
    <<: *django
    command: celery -A core beat -l INFO
    depends_on:
      - redis
      - db

  flower:
    <<: *django
    command: celery -A core --broker="redis://redis:6379/0" flower
    ports:
      - 15557:5555
    depends_on:
      - redis
      - db

volumes:
  postgres_data:
  redis_data:
