# Generated by Django 5.1.2 on 2024-10-12 18:16

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Job',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=255)),
                ('company', models.CharField(max_length=255)),
                ('location', models.CharField(max_length=255)),
                ('is_remote', models.BooleanField(default=False)),
                ('job_type', models.CharField(choices=[('FT', 'Full-Time'), ('PT', 'Part-Time'), ('FR', 'Freelance'), ('CT', 'Contract'), ('IN', 'Internship'), ('VT', 'Volunteer')], default='FT', max_length=2)),
                ('description', models.TextField()),
                ('pay_range', models.CharField(blank=True, max_length=100, null=True)),
                ('pay_frequency', models.CharField(choices=[('SA', 'Salary'), ('HR', 'Hourly'), ('PD', 'Per Diem'), ('OT', 'One-time'), ('NA', 'N/A')], default='SA', max_length=2)),
                ('application_email', models.EmailField(blank=True, max_length=254, null=True)),
                ('application_link', models.URLField(blank=True, null=True)),
            ],
            options={
                'ordering': ['-created_at'],
                'abstract': False,
            },
        ),
    ]
