# Generated by Django 5.1.2 on 2025-03-10 21:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0001_initial'),
        ('scraper', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='source',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='scraper.jobsource'),
        ),
    ]
