# Generated by Django 5.1.2 on 2025-03-19 15:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='organization',
            name='job_listing_url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
